<a href="https://colab.research.google.com/github/dani118089/assingment/blob/main/numpyassingment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix --------------------------------------------------------------------------------------

In [72]:
import numpy as np
x=np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [73]:
x=np.reshape(x,(4,10))
x

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [74]:
x[0:,9:]

array([[19],
       [29],
       [39],
       [49]])

2. Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result -------------------------------------------------------------

In [75]:
import numpy as np
x=np.arange(1,10).reshape(3,3)
x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
y=np.full((3,3),5)
y

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [77]:
np.add(x,y)

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [78]:
a=np.multiply(x,y)
a

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
np.transpose(a)

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

-------------------------------------------------------------------------------------------------------------------------------
3. Create a NumPy array of 15 random integers between 10 and 100.
● Replace all values greater than 50 with -1
● Count how many values were replaced.

In [80]:
import numpy as np
rand=np.random.randint(10,101,15)
print(rand)


[43 15 73 13 87 20 92 87 67 58 54 64 67 54 74]


In [81]:
#  Replace all values greater than 50 with -1
rand [rand>50]=-1
rand

array([43, 15, -1, 13, -1, 20, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [82]:
cound =np.count_nonzero(rand == -1)
print(cound)

11


In [83]:
# 4. Generate a 5×4 array with random values between 0 and 1 (float).
# ● Find the row with the maximum sum of values.
# ● Normalize each row using the formula:

import numpy as np

rand = np.random.rand(5, 4)
print(rand)

[[0.70587246 0.13573024 0.36025552 0.8935123 ]
 [0.69789179 0.12539902 0.59324036 0.84188718]
 [0.56468605 0.73474575 0.14600118 0.82794149]
 [0.21207295 0.16487026 0.75987733 0.35069875]
 [0.40498574 0.88502269 0.42538145 0.33935563]]


In [84]:
#  ● Find the row with the maximum sum of values.
fnsum=np.sum(rand,axis=1)
fnsum


array([2.09537052, 2.25841836, 2.27337446, 1.48751928, 2.05474552])

In [85]:
bigrw=np.argmax(fnsum)
bigrw

np.int64(2)

In [86]:
Min=np.min(rand,axis=1,keepdims=True)
Max=np.max(rand,axis=1,keepdims=True)
normalized = (rand - Min) / (Max - Min)
normalized


array([[0.75238285, 0.        , 0.29629268, 1.        ],
       [0.79902615, 0.        , 0.65296451, 1.        ],
       [0.61396117, 0.8633374 , 0.        , 1.        ],
       [0.07933131, 0.        , 1.        , 0.31231309],
       [0.12027502, 1.        , 0.15765259, 0.        ]])

In [87]:
# 5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
# ● Find all unique elements
# ● Find the duplicates (elements that appear more than once)
import numpy as np
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
print(np.unique(arr))

[1 3 5 7 9]


In [88]:

unique_elements,counts=np.unique(arr,return_counts=True)
duplicates=unique_counts[counts>1]
print(duplicates)

[1 3 5]


In [89]:
# 6. Create a 6×6 NumPy array with values from 1 to 36.
# ● Extract the middle 4×4 submatrix.
# ● Then extract all even numbers from this submatrix.

import numpy as np
arr=np.array(range(1,37)).reshape(6,6)
print(arr)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [90]:
submatrix=arr[1:5,1:5]
submatrix

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [91]:
even=submatrix[submatrix%2==0]
even

array([ 8, 10, 14, 16, 20, 22, 26, 28])

In [92]:
# 7. Generate an array of shape (3, 4) with values from 0 to 11.
# ● Reshape it to (2, 6)
# ● Then flatten it into a 1D array
# ● Convert the 1D array back to shape (4, 3)

import numpy as np
arry=np.array(range(0,12)).reshape(3,4)
arry

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
arry.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [94]:
x = arry.flatten()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
x.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [96]:
# 8 . Create an array: a = np.array([[1, 2], [3, 4]])
# ● Append a new row [5, 6]
# ● Then append a new column [7, 8, 9]


import numpy as np
ary = np.array([[1, 2], [3, 4]])
ary


array([[1, 2],
       [3, 4]])

In [97]:
new_row=np.array([[5,6]])
x=np.append(ary,new_row,axis=0)
x


array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
new_col = np.array([[7],
                    [8],
                    [9]])
y = np.append(x, new_col, axis=1)
print(y)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


In [103]:
# 9.
# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
# c = np.array([7, 8, 9])
# ● Join them into a single array
# ● Reshape the result into a 3×3 matrix
# ● Extract the diagonal elements



import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
aryy= np.concatenate((a,b,c))
aryy


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
matrix = aryy.reshape(3, 3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
diag = np.diagonal(matrix)
print(diag)

[1 5 9]


In [111]:
# 10. Create a NumPy array of integers from 1 to 20.
# ● Extract all values that are divisible by 3 or 5.
# ● Count how many such values exist


import numpy as np
aray=np.array(range(1,21))
aray


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [113]:
divs=aray[(aray%3==0)  |  (aray%5==0)]
divs

array([ 3,  5,  6,  9, 10, 12, 15, 18, 20])

In [114]:
count=divs.size
count

9

In [115]:
x=len(divs)
x

9